# Copyright 2025 Bitshift D.O.O
# SPDX-License-Identifier: MPL-2.0

---
- name: Copy scripts
  ansible.builtin.template:
    src: setup-route.sh.j2
    dest: /tmp/setup-route.sh
    owner: root
    group: root
    mode: '0755'
- name: Execute scripts
  ansible.builtin.command:
    cmd: /tmp/setup-route.sh
    creates: /tmp/setup-route.sh.done
- name: Copy persistent configuration
  ansible.builtin.template:
    src: network-setup.j2
    dest: "/etc/systemd/network/10-{{ private_interface }}.network"
    owner: root
    group: root
    mode: '0644'
- name: Configure DNS servers
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: ^#DNS=
    line: "DNS={{ dns_servers }}"
- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    enabled: true
- name: Install ACL package
  ansible.builtin.apt:
    name: acl
    state: present
    update_cache: true
